sudo: required

services: docker

before_install:
  - docker-compose up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script:
  - docker-compose exec --env 'RAILS_ENV=test' app rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' app rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' app rails db:seed
  - docker-compose exec --env 'RAILS_ENV=test' app RAILS_ENV=test bundle exec rails webpacker:compile
  - docker-compose exec --env 'RAILS_ENV=test' app bundle exec rspec spec/models/user_spec.rb
  - docker-compose exec --env 'RAILS_ENV=test' app bundle exec rspec spec/system/users_spec.rb

deploy:
  provider: script
  script: 
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
    heroku run --app $HEROKU_APP_NAME rails db:seed;
  on:
    branch: master